const express = require("express")
const route =require("./routes")
const bp = require("body-parser")
const mongoose = require("mongoose")
const config = require("./config")

const app = express()
mongoose.set('strictQuery', true)
mongoose.connect(config.mongoUrl)
app.use(bp.json())
app.use(bp.urlencoded({extended:false}))
app.use('/imgs',express.static('imgs'))
app.use(route)
app.listen(config.appPort)