const express = require("express")
const route =require("./routes")
const bp = require("body-parser")
const mongoose = require("mongoose")
const config = require("./config")
const app = express()
mongoose.connect(config.mongoUrl)
app.use(bp.urlencoded({extended:true}))
app.use(route)
app.listen(config.appPort)