const express = require("express")
const { pAdd, login, pQuery,oQuery,dQuery,dpQuery,authenticateToken,upload,oAdd,dAdd } = require("./op")
const route = express.Router()
route.post("/pAdd",upload.single("singleFile"),pAdd)
route.post("/oAdd",authenticateToken,oAdd)
route.post("/dAdd",authenticateToken,dAdd)
route.post("/login",login)
route.post("/pQuery",authenticateToken,pQuery)
route.post("/oQuery",authenticateToken,oQuery)
route.post("/dQuery",dQuery)
route.post("/dpQuery",dpQuery)
module.exports = route